repos:
  - repo: local
    hooks:
      - id: ruff
        name: Run ruff via uv
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: Format with ruff via uv
        entry: uv run ruff format
        language: system
        types: [python]